# Лабораторная работа 7

## Numpy, файлы, CSV


In [1]:
import csv
import random
import timeit
from pathlib import Path

import numpy as np
from PIL import Image


## Numpy

### №1
Используя средства библиотеки Numpy, без циклов, выполните следующие задания:

a) Создайте массив `arr_1` размером `3x4`, все элементы которого равны `3`.
b) Создайте массив `arr_2`, заполненный случайными целыми числами от `0` до `9`, размером `2x4`.
c) Выведите на экран количество элементов в созданных массивах `arr_1` и `arr_2`.
d) Соедините массивы `arr_1` и `arr_2` по нулевой оси.
e) Создайте массив `arr_3` из кортежа чисел `(1, 8, 6, 5, 8, 3)` с помощью функции `np.array()`.
f) Умножьте каждый элемент массива `arr_3` на число `3` и прибавьте к каждому элементу `1`. Результат запишите в новый массив `arr_4`.
g) Преобразуйте массив `arr_3` к двумерному массиву `2x3`. Результат запишите в массив `arr_5`.
h) Определите минимальные элементы массива `arr_5` вдоль первой оси.
i) Вычислите среднее арифметическое всех элементов массива `arr_5`.
j) Создайте массив `arr_6`, состоящий из квадратов чисел от `0` до `10`.
k) Выведите каждый второй элемент массива `arr_6`.
l) Выведите элементы массива `arr_6` в обратном порядке.
m) Каждому второму элементу массива `arr_6` присвойте значение `2`.
n) Проверьте, есть ли в массиве `arr_6` значение `49`.
o) Создайте двумерный массив `A`, состоящий из положительных и отрицательных чисел. Из массива `A` выберите все отрицательные элементы и запишите их в одномерный массив `B`.


In [2]:
rng = np.random.default_rng(42)

arr_1 = np.full((3, 4), 3)
arr_2 = rng.integers(0, 10, size=(2, 4))
arr_1_size = arr_1.size
arr_2_size = arr_2.size
arr_joined = np.concatenate((arr_1, arr_2), axis=0)

arr_3 = np.array((1, 8, 6, 5, 8, 3))
arr_4 = arr_3 * 3 + 1
arr_5 = arr_3.reshape(2, 3)
arr_5_min = arr_5.min(axis=0)
arr_5_mean = arr_5.mean()

arr_6 = np.arange(11) ** 2
arr_6_every_second = arr_6[::2]
arr_6_reversed = arr_6[::-1]
arr_6_modified = arr_6.copy()
arr_6_modified[1::2] = 2
has_49 = np.any(arr_6_modified == 49)

A = np.array([[3, -1, 7], [-5, 2, -8]])
B = A[A < 0]

print("arr_1:\n", arr_1)
print("arr_2:\n", arr_2)
print("Количество элементов:", arr_1_size, arr_2_size)
print("Объединение по нулевой оси:\n", arr_joined)
print("arr_3:", arr_3)
print("arr_4:", arr_4)
print("arr_5:\n", arr_5)
print("Минимумы по первой оси:", arr_5_min)
print("Среднее arr_5:", arr_5_mean)
print("arr_6:", arr_6)
print("Каждый второй элемент:", arr_6_every_second)
print("В обратном порядке:", arr_6_reversed)
print("После замены каждого второго элемента:\n", arr_6_modified)
print("Есть ли 49:", has_49)
print("Массив A:\n", A)
print("Отрицательные элементы B:", B)


arr_1:
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
arr_2:
 [[0 7 6 4]
 [4 8 0 6]]
Количество элементов: 12 8
Объединение по нулевой оси:
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [0 7 6 4]
 [4 8 0 6]]
arr_3: [1 8 6 5 8 3]
arr_4: [ 4 25 19 16 25 10]
arr_5:
 [[1 8 6]
 [5 8 3]]
Минимумы по первой оси: [1 8 3]
Среднее arr_5: 5.166666666666667
arr_6: [  0   1   4   9  16  25  36  49  64  81 100]
Каждый второй элемент: [  0   4  16  36  64 100]
В обратном порядке: [100  81  64  49  36  25  16   9   4   1   0]
После замены каждого второго элемента:
 [  0   2   4   2  16   2  36   2  64   2 100]
Есть ли 49: False
Массив A:
 [[ 3 -1  7]
 [-5  2 -8]]
Отрицательные элементы B: [-1 -5 -8]


### №2
Представьте, что вы пишете компьютерную игру «Шахматы».

Вам надо смоделировать шахматную доску, которая представляет собой numpy-матрицу. Чёрная клетка представляется нулём, а белая — единицей. Если смотреть на доску сверху, то левая верхняя клетка — белая.

Вы уже практически реализовали задачу, ведь вы знаете, что у шахматной доски `8` столбцов и `8` строк, но заказчик вдруг изменил требования и заявил, что в его игре доска может быть произвольного размера, но всегда квадратной, например, `50x50`.

Напишите функцию `make_field(size)`, в которую поступает размер доски, и которая возвращает требуемый массив numpy. Тип элементов массива должен быть `np.int8`.

Для решения задачи нельзя использовать циклы.


In [3]:
def make_field(size):
    board = np.indices((size, size)).sum(axis=0) % 2
    return (1 - board).astype(np.int8)


print(make_field(8))


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


### №3
Напишите функцию `super_sort(rows, cols)`, в которую поступают размеры матрицы. Вам необходимо:

- заполнить матрицу `A` случайными целыми числами из диапазона `[1..100]`
- сделать копию этой матрицы в матрицу `B`
- упорядочить чётные столбцы матрицы `B` по возрастанию, а нечётные — по убыванию

Верните кортеж, состоящий из матриц `A` и `B`.

Для решения задачи нельзя использовать циклы. Для сортировки используйте функцию `np.sort`.


In [4]:
def super_sort(rows, cols, seed=None):
    rng = np.random.default_rng(seed)
    A = rng.integers(1, 101, size=(rows, cols))
    B = A.copy()
    B[:, 1::2] = np.sort(B[:, 1::2], axis=0)
    B[:, 0::2] = np.sort(B[:, 0::2], axis=0)[::-1]
    return A, B


A_sorted, B_sorted = super_sort(5, 6, seed=7)
print("A:\n", A_sorted)
print("B:\n", B_sorted)


A:
 [[ 95  63  69  90  58  78]
 [ 84  23   6  31  29  88]
 [ 92   1  50  83  14  80]
 [ 12  47  82  31  35  28]
 [ 72  26 100  45  48  51]]
B:
 [[ 95   1 100  31  58  28]
 [ 92  23  82  31  48  51]
 [ 84  26  69  45  35  78]
 [ 72  47  50  83  29  80]
 [ 12  63   6  90  14  88]]


### №4
Создайте массив чисел от `-2π` до `2π`. Посчитайте сумму поэлементных квадратов синуса и косинуса для данного массива. С помощью `np.all` проверьте, что в ответе только единицы.


In [5]:
angles = np.linspace(-2 * np.pi, 2 * np.pi, 1000)
values = np.sin(angles) ** 2 + np.cos(angles) ** 2

print(values[:5])
print("Все элементы близки к единице:", np.all(np.isclose(values, 1)))


[1. 1. 1. 1. 1.]
Все элементы близки к единице: True


### №5
Создайте две numpy матрицы размера `n x n` и заполните их случайными значениями. Посчитайте их поэлементное и матричное произведения. Для этого реализуйте функции:

1. `mult` – матричное перемножение без использования numpy
2. `el_mult` – поэлементное перемножение без использования numpy
3. `np_mult` – матричное перемножение c использованием numpy
4. `np_el_mult` – поэлементное перемножение с использованием numpy

При помощи `timeit` засеките время работы функций для `n = 100000` (для чистоты эксперимента засекать время на одинаковых матрицах). Во сколько раз numpy версия функций работает быстрее реализаций без numpy?


In [ ]:
def mult(a, b):
    rows = len(a)
    cols = len(b[0])
    common = len(b)
    return [
        [sum(a[i][k] * b[k][j] for k in range(common)) for j in range(cols)]
        for i in range(rows)
    ]


def el_mult(a, b):
    rows = len(a)
    cols = len(a[0])
    return [[a[i][j] * b[i][j] for j in range(cols)] for i in range(rows)]


def np_mult(a, b):
    return a @ b


def np_el_mult(a, b):
    return a * b


demo_n = 4
rng = np.random.default_rng(10)
matrix_a = rng.integers(0, 10, size=(demo_n, demo_n))
matrix_b = rng.integers(0, 10, size=(demo_n, demo_n))

print("Матрица A:\n", matrix_a)
print("Матрица B:\n", matrix_b)
print("mult(A, B):\n", np.array(mult(matrix_a.tolist(), matrix_b.tolist())))
print("el_mult(A, B):\n", np.array(el_mult(matrix_a.tolist(), matrix_b.tolist())))
print("np_mult(A, B):\n", np_mult(matrix_a, matrix_b))
print("np_el_mult(A, B):\n", np_el_mult(matrix_a, matrix_b))

benchmark_n = 80
rng = np.random.default_rng(11)
bench_a_np = rng.random((benchmark_n, benchmark_n))
bench_b_np = rng.random((benchmark_n, benchmark_n))
bench_a_list = bench_a_np.tolist()
bench_b_list = bench_b_np.tolist()

pure_matmul_time = timeit.timeit(lambda: mult(bench_a_list, bench_b_list), number=1)
pure_elem_time = timeit.timeit(lambda: el_mult(bench_a_list, bench_b_list), number=3)
np_matmul_time = timeit.timeit(lambda: np_mult(bench_a_np, bench_b_np), number=3)
np_elem_time = timeit.timeit(lambda: np_el_mult(bench_a_np, bench_b_np), number=1000)

print("\nБенчмарк на размере", benchmark_n)
print("Матричное умножение без numpy:", pure_matmul_time)
print("Матричное умножение с numpy:", np_matmul_time)
print("Поэлементное умножение без numpy:", pure_elem_time)
print("Поэлементное умножение с numpy:", np_elem_time)
print("Ускорение матричного умножения:", pure_matmul_time / np_matmul_time)
print("Ускорение поэлементного умножения:", pure_elem_time / np_elem_time)


Матрица A:
 [[7 9 2 2]
 [7 8 5 1]
 [8 5 1 1]
 [4 6 4 8]]
Матрица B:
 [[0 4 5 9]
 [2 8 0 3]
 [7 5 9 7]
 [9 8 1 9]]
mult(A, B):
 [[ 50 126  55 122]
 [ 60 125  81 131]
 [ 26  85  50 103]
 [112 148  64 154]]
el_mult(A, B):
 [[ 0 36 10 18]
 [14 64  0  3]
 [56 25  9  7]
 [36 48  4 72]]
np_mult(A, B):
 [[ 50 126  55 122]
 [ 60 125  81 131]
 [ 26  85  50 103]
 [112 148  64 154]]
np_el_mult(A, B):
 [[ 0 36 10 18]
 [14 64  0  3]
 [56 25  9  7]
 [36 48  4 72]]

Бенчмарк на размере 80
Матричное умножение без numpy: 0.04054454200377222
Матричное умножение с numpy: 0.00011262499901931733
Поэлементное умножение без numpy: 0.0008062499982770532
Поэлементное умножение с numpy: 0.001181792002171278
Ускорение матричного умножения: 359.995936575485
Ускорение поэлементного умножения: 0.682226649694489


### №6
В статистике и задачах машинного обучения часто приходится иметь дело с функцией, которая вычисляется по формуле `∑(y_i - a_i)^2`, где `i` меняется от `1` до `n`, `y_i` — координаты одномерного вектора `y`, `a_i` — координаты одномерного вектора `a`.

Посчитайте для `y = (1, 2, 3, 4, 5)`, `a = (3, 2, 1, 0, -1)`.


In [7]:
y = np.array([1, 2, 3, 4, 5])
a = np.array([3, 2, 1, 0, -1])
loss = np.sum((y - a) ** 2)

print(loss)


60


### №7
Подумайте, массив какого размера получится, если перемножить массив `4x1x3` и массив `12x1`.
Убедитесь на практике в правильности вашего ответа.


In [8]:
first = np.arange(12).reshape(4, 1, 3)
second = np.arange(12).reshape(12, 1)
result = first * second

print("Форма первого массива:", first.shape)
print("Форма второго массива:", second.shape)
print("Форма результата:", result.shape)


Форма первого массива: (4, 1, 3)
Форма второго массива: (12, 1)
Форма результата: (4, 12, 3)


### №8
Создайте и заполните случайными значениями матрицы `A`, `B`, `C` и `D` (размерности смотрите в формуле). Вычислите следующее выражение:

`5 · A_(n,m) · B_(m) + C^T_(m,n) · D_(m)`


In [9]:
n, m = 3, 4
rng = np.random.default_rng(12)

A = rng.integers(-5, 6, size=(n, m))
B = rng.integers(-5, 6, size=m)
C = rng.integers(-5, 6, size=(m, n))
D = rng.integers(-5, 6, size=m)

expression = 5 * (A @ B) + (C.T @ D)

print("A:\n", A)
print("B:", B)
print("C:\n", C)
print("D:", D)
print("Результат:\n", expression)


A:
 [[ 1 -3  5  5]
 [-5 -3 -3 -4]
 [ 1 -2  0 -3]]
B: [ 5  2  2 -4]
C:
 [[-4  4 -2]
 [ 4  3 -5]
 [ 0  0  0]
 [-4  2 -3]]
D: [-2 -1 -2 -1]
Результат:
 [ -47 -118   77]


### №9
В машинном обучении есть модель линейной регрессии, для которой «хорошее» решение считается по следующей формуле:

`θ̂ = (X^T · X + λ · I_n)^(-1) · X^T y`

Вычислите результат формулы для:

`X = [[-3, 4, 1], [4, 3, 1]]`, `y = [10, 12]`, `I_n` — единичная матрица размерности `3`, `λ = 0.1`.


In [10]:
X = np.array([[-3, 4, 1], [4, 3, 1]], dtype=float)
y = np.array([10, 12], dtype=float)
lam = 0.1
I_n = np.eye(3)

theta = np.linalg.inv(X.T @ X + lam * I_n) @ X.T @ y
print(theta)


[0.68478852 2.80148778 0.81180812]


### №10
Напишите программу, которая будет решать систему линейных уравнений вида:

```
a11 * x + a12 * y = b1
a21 * x + a22 * y = b2
```

Коэффициенты и правую часть вводит пользователь. Программа выводит решение системы. Для нахождения решения используйте `numpy.linalg.solve`.

Система не имеет решения (или имеет их бесконечно много), если определитель матрицы коэффициентов равен `0`. В этом случае необходимо выводить соответствующее сообщение. Для нахождения определителя используйте функцию `numpy.linalg.det`.


In [11]:
def solve_linear_system(a11, a12, b1, a21, a22, b2):
    matrix = np.array([[a11, a12], [a21, a22]], dtype=float)
    rhs = np.array([b1, b2], dtype=float)

    if np.isclose(np.linalg.det(matrix), 0):
        return "Система не имеет единственного решения."

    return np.linalg.solve(matrix, rhs)


print(solve_linear_system(2, 1, 5, 1, -1, 1))
print(solve_linear_system(1, 2, 3, 2, 4, 6))


[2. 1.]
Система не имеет единственного решения.


### №11
Используя numpy, без питоновских циклов сконвертируйте цветное изображение в чёрно-белое по формуле:

`C = 0.2989 * R + 0.5870 * G + 0.1140 * B`

Считается, что вычисленный таким образом цвет лучше всего подходит для человеческого глаза, поскольку яркость каждой компоненты глаз воспринимает по-разному.

Напишите функцию `bw_convert()`, в которой проведите все необходимые операции.
Не забудьте, что значение каждой составляющей цвета — целое число, поэтому результат необходимо округлить. Для этого воспользуйтесь методом `round()` из библиотеки numpy.
Используйте формат изображения `RGB` и библиотеку `pillow`.


In [12]:
def bw_convert(input_path, output_path):
    rgb = np.array(Image.open(input_path).convert("RGB"), dtype=np.float64)
    gray = np.round(0.2989 * rgb[:, :, 0] + 0.5870 * rgb[:, :, 1] + 0.1140 * rgb[:, :, 2])
    gray = np.clip(gray, 0, 255).astype(np.uint8)
    Image.fromarray(gray, mode="L").save(output_path)
    return gray


rgb_demo = np.array(
    [
        [[255, 0, 0], [0, 255, 0], [0, 0, 255]],
        [[255, 255, 0], [255, 255, 255], [0, 0, 0]],
    ],
    dtype=np.uint8,
)
demo_input = Path("task11_input.png")
demo_output = Path("task11_output.png")
Image.fromarray(rgb_demo, mode="RGB").save(demo_input)

gray_demo = bw_convert(demo_input, demo_output)
print(gray_demo)
print("Файл сохранён:", demo_output)


[[ 76 150  29]
 [226 255   0]]
Файл сохранён: task11_output.png


### №12
В материалах к лабораторной работе лежит файл `ABBREV.csv`. Это – текстовый файл в кодировке `UTF-8`, в котором записана таблица данных, а данные в строчках разделены символом «точка-с-запятой».

Файл создан департаментом сельского хозяйства США и в нём указаны продукты и содержание в них некоторых витаминов, минералов, а также калорийность на единицу массы.

Для чтения данных из этого файла в объект `numpy.ndarray` воспользуйтесь методом `genfromtxt()` из библиотеки numpy.

```python
table = np.genfromtxt('ABBREV.csv', delimiter=';', dtype=None, names=True, encoding='utf8')
```

Вычислите и выведите на отдельных строчках названия самого-самого продукта по различным критериям.

- Самый калорийный. Если их несколько, то выведите тот, у кого название в словаре стоит позже всех других.
- Самый полезный по содержанию сахара. Если их много, то выведите тот, у кого название в словаре стоит на первом месте.
- Самый протеино-накачанный. Если имеется несколько вариантов, то снова выведите младший в словаре по названию.
- Самый богатый витамином C. Такой продукт точно один.

Помните, что «самый-самый» – это не обязательно максимальная характеристика.
Поиск продуктов необходимо выполнять только c использованием средств библиотеки numpy.


In [13]:
def choose_product(table, field, mode="max", lex="first"):
    values = table[field]
    names = table["Shrt_Desc"]
    target = values.max() if mode == "max" else values.min()
    idx = np.flatnonzero(values == target)
    ordered = idx[np.argsort(names[idx])]
    return names[ordered[0] if lex == "first" else ordered[-1]]


table = np.genfromtxt(
    "материалы к лабе/ABBREV.csv",
    delimiter=";",
    dtype=None,
    names=True,
    encoding="utf8",
)

print(choose_product(table, "Energ_Kcal", mode="max", lex="last"))
print(choose_product(table, "Sugar_Tot_g", mode="min", lex="first"))
print(choose_product(table, "Protein_g", mode="max", lex="first"))
print(choose_product(table, "Vit_C_mg", mode="max", lex="first"))


LARD
"BEEF COMP.LN.1/8"" FAT.CHOIC.CKD"
SOY PROT ISOLATE.K TYPE
BABYFOOD.GERBER.2ND FOODS.APPL.CARROT & SQUASH.ORGANIC


## Файлы в Python

### №13
У вас есть некоторый файл `lines.txt`, состоящий из нескольких строк.

Вам необходимо вывести на экран случайную строку из этого файла. Файл может быть пустым, тогда и выводить ничего не надо.


In [14]:
def random_line(path, seed=None):
    lines = Path(path).read_text(encoding="utf-8").splitlines()
    if not lines:
        return None
    rng = random.Random(seed)
    return rng.choice(lines)


Path("lines.txt").write_text("первая строка\nвторая строка\nтретья строка\n", encoding="utf-8")
print(random_line("lines.txt", seed=5))


третья строка


### №14
Напишите функцию `reverse()`, которая побайтно читает бинарные данные из файла `input.dat` и создаёт файл `output.dat`, куда сохраняет прочитанные данные в обратном порядке.

Постарайтесь решить эту задачу без использования циклов.


In [15]:
def reverse(input_path="input.dat", output_path="output.dat"):
    data = Path(input_path).read_bytes()
    Path(output_path).write_bytes(data[::-1])


Path("input.dat").write_bytes(b"abcdef")
reverse()
print(Path("output.dat").read_bytes())


b'fedcba'


### №15
В текстовом файле `input.txt` через пробельные символы (пробел, табуляция, перевод строки и т.д.) записаны целые числа — данные, полученные с некоторого устройства. Количество их неизвестно.

Вам необходимо:
Посчитать количество положительных, отрицательных и нулевых значений в исходном файле.

Вывести в файл `output.txt` в первую строку количество всех чисел исходного файла, а во вторую — посчитанные значения через пробел в порядке их убывания в следующем виде: `<метка> <значение> <метка> <значение> <метка> <значение>`, где

- `1` — метка положительных чисел
- `-1` — метка отрицательных чисел
- `0` — метка нуля

Если каких-либо данных (например, положительных) во входном наборе нет, то и выводить их не обязательно, однако суммарное количество требуется печатать в любом случае.


In [16]:
def count_values(input_path="input.txt", output_path="output.txt"):
    content = Path(input_path).read_text(encoding="utf-8").split()
    numbers = list(map(int, content)) if content else []
    counts = {
        1: sum(number > 0 for number in numbers),
        -1: sum(number < 0 for number in numbers),
        0: sum(number == 0 for number in numbers),
    }
    ordered = sorted(
        ((label, count) for label, count in counts.items() if count > 0),
        key=lambda item: item[1],
        reverse=True,
    )

    lines_out = [str(len(numbers))]
    if ordered:
        lines_out.append(" ".join(f"{label} {count}" for label, count in ordered))

    Path(output_path).write_text("\n".join(lines_out), encoding="utf-8")


Path("input.txt").write_text("1 -5 0 7 0 -3 9 4", encoding="utf-8")
count_values()
print(Path("output.txt").read_text(encoding="utf-8"))


8
1 4 -1 2 0 2


### №16
На вход программе подаётся BMP-файл, содержащий некоторое изображение. Без использования сторонних графических библиотек (например, `PIL`) сформируйте новый файл, в который сохраните негатив, полученный из исходного изображения.

У BMP-файла очень простая структура. Первые `54` байта являются заголовком, и их нужно оставить без изменения. А все остальные байты надо заменить на значение, вычисленное как `255 - value`, где `value` — это значение прочитанного байта.

Операции чтения и записи следует осуществлять в двоичном режиме (как поток байт).
В этом вам поможет класс `bytes`. Объекты этого класса получаются в результате чтения файла в бинарном режиме.
Работа с элементами `bytes` аналогична списку. Список также можно преобразовать в поток байт:

```python
data = bytes([1, 2, 3])
```


In [17]:
def bmp_negative(input_path, output_path):
    data = Path(input_path).read_bytes()
    header, pixels = data[:54], data[54:]
    negative_pixels = bytes(255 - value for value in pixels)
    Path(output_path).write_bytes(header + negative_pixels)


demo_bmp = Path("demo.bmp")
demo_negative = Path("demo_negative.bmp")
Image.new("RGB", (2, 2), color=(20, 40, 60)).save(demo_bmp)
bmp_negative(demo_bmp, demo_negative)
print("Созданы файлы:", demo_bmp, demo_negative)


Созданы файлы: demo.bmp demo_negative.bmp


## Модуль CSV

### №17
В `csv` файле хранится информация о продуктах: название, старая и новая цены. Цены указаны в копейках.

Выведите на экран в порядке упоминания в файле те товары, цена на которые уменьшилась.
Если товаров, попадающих под условие задачи, нет, то на экран выводить ничего не надо.
Для быстрого решения задачи воспользуйтесь объектом `DictReader`.


In [18]:
def discounted_products(path):
    result = []
    with open(path, encoding="utf-8", newline="") as file:
        reader = csv.DictReader(file)
        for row in reader:
            if int(row["new_price"]) < int(row["old_price"]):
                result.append(row["name"])
    return result


with open("prices.csv", "w", encoding="utf-8", newline="") as file:
    writer = csv.DictWriter(file, fieldnames=["name", "old_price", "new_price"])
    writer.writeheader()
    writer.writerows(
        [
            {"name": "Хлеб", "old_price": 4590, "new_price": 4390},
            {"name": "Молоко", "old_price": 8990, "new_price": 8990},
            {"name": "Сыр", "old_price": 18990, "new_price": 17990},
        ]
    )

print(*discounted_products("prices.csv"), sep="\n")


Хлеб
Сыр


### №18
В файле `rez.csv` (он лежит в папке с материалами) содержатся результаты олимпиады:

`place,user_name,login,"1(Система счисления)","2(Количество символов)","3(Минимальное число)","4(Трамвай)","Score"`

Т.е. место, имя участника, логин, названия четырёх задач и сумма баллов.
Поля отделяются `,`. Каждая запись об участнике находится в отдельной строке.

Логин участника имеет вид `sh-kaluga16-**-##-@`, где `**` — номер школы, а `##` — номер класса, `@` — номер участника.

Например:

```
1-4,"У 09 11 Иванов И","sh-kaluga16-09-11-1","100(+)","100(+)","100(+1)","0(+3)","300"
1-4,"У 01 09 Петров П","sh-kaluga16-01-09-1","100(+2)","100(+1)","100(+)","","300"
```

Определите результаты олимпиады для указанной школы и класса.

Ваша программа должна вывести имена всех участников и балл через пробел из данной школы и класса в порядке убывания балла. При совпадении баллов фамилии нужно выводить в обратном алфавитном порядке. Информацию о каждом участнике надо выводить с новой строки.


In [19]:
def olympiad_results(path, school, grade):
    rows = []
    with open(path, encoding="utf-8-sig", newline="") as file:
        reader = csv.DictReader(file)
        for row in reader:
            parts = row["login"].split("-")
            if len(parts) < 5:
                continue
            if parts[2] == school and parts[3] == grade:
                name_parts = row["user_name"].split()
                surname = name_parts[3] if len(name_parts) >= 4 else row["user_name"]
                rows.append((row["user_name"], int(row["Score"]), surname))

    rows.sort(key=lambda item: (item[1], item[2]), reverse=True)
    return [f"{name} {score}" for name, score, _ in rows]


print(*olympiad_results("материалы к лабе/rez.csv", "09", "11"), sep="\n")


У 09 11 Макеев В 300
У 09 11 Царьклова А 270
У 09 11 Лапа Н 260
